name: Lint and Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'

    - name: Install Python dependencies
      run: make build-server

    - name: Run Python linting
      run: make lint-server

    - name: Run Python tests
      run: make test-server

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run TypeScript linting
      run: |
        npm install eslint
        npx eslint src/**/*.tsx

    - name: Run React tests
      run: npm test