name: Lint and Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'

    - name: Install Python dependencies
      run: |
        cd backend
        make build-server

    - name: Run Python linting
      run: |
        cd backend
        make lint-server

    - name: Run Python tests
      env:
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      run: |
        cd backend
        make test-server

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'

    - name: Install Node.js dependencies
      run: |
        cd frontend
        make build-client

    - name: Run TypeScript linting
      run: |
        cd frontend
        make lint-client